name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x android-app/gradlew
      
    - name: Build Debug APK
      run: |
        cd android-app
        ./gradlew assembleDebug --stacktrace
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: AutoGLM-Helper-Debug
        path: android-app/app/build/outputs/apk/debug/app-debug.apk
        
    - name: Create Release APK (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        cd android-app
        ./gradlew assembleRelease --stacktrace
        
    - name: Upload Release APK (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v4
      with:
        name: AutoGLM-Helper-Release
        path: android-app/app/build/outputs/apk/release/app-release.apk
